export const iconMap: Record<string, string> = {
    "01d": "clear-day.svg",
    "01n": "clear-night.svg",
    "02d": "partly-cloudy-day.svg",
    "02n": "partly-cloudy-night.svg",
    "03d": "cloudy.svg",
    "03n": "cloudy.svg",
    "04d": "overcast-day.svg",
    "04n": "overcast-night.svg",
    "09d": "drizzle.svg",
    "09n": "drizzle.svg",
    "10d": "rain.svg",
    "10n": "rain.svg",
    "11d": "thunderstorms-day.svg",
    "11n": "thunderstorms-night.svg",
    "13d": "snow.svg",
    "13n": "snow.svg",
    "50d": "fog-day.svg",
    "50n": "fog-night.svg",
  };